// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxlcgekggsojggybchcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bGNnZWtnZ3NvamdneWJjaGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzMxMDgsImV4cCI6MjA3NDY0OTEwOH0._pIFhLOJuS2zG43JhGiolGb0p0l1pwNZsrw39HbNAaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});