name: Check Supabase Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test proxy-nasa-data function
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          set -e
          echo "Calling proxy-nasa-data..."
          URL="${SUPABASE_URL%/}/functions/v1/proxy-nasa-data?lat=37.7749&lon=-122.4194&startDate=2025-09-20&endDate=2025-09-21"
          echo "URL: $URL"
          RESP=$(curl -sS -w "\n%{http_code}" -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" -H "apikey: ${SUPABASE_ANON_KEY}" "$URL")
          BODY=$(echo "$RESP" | sed '$d')
          CODE=$(echo "$RESP" | tail -n1)
          echo "HTTP $CODE"
          echo "$BODY" > proxy_response.txt
          if [ "$CODE" -ge 400 ]; then
            echo "Error response from proxy-nasa-data (exit 1)."
            cat proxy_response.txt
            exit 1
          fi

      - name: Upload proxy response
        uses: actions/upload-artifact@v4
        with:
          name: proxy-response
          path: proxy_response.txt

      - name: Test get-weather function
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          set -e
          echo "Calling get-weather..."
          URL="${SUPABASE_URL%/}/functions/v1/get-weather"
          echo "URL: $URL"
          RESP=$(curl -sS -w "\n%{http_code}" -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" -H "apikey: ${SUPABASE_ANON_KEY}" -H "Content-Type: application/json" -d '{"lat":37.7749,"lon":-122.4194}' "$URL")
          BODY=$(echo "$RESP" | sed '$d')
          CODE=$(echo "$RESP" | tail -n1)
          echo "HTTP $CODE"
          echo "$BODY" > get_weather_response.txt
          if [ "$CODE" -ge 400 ]; then
            echo "Error response from get-weather (exit 1)."
            cat get_weather_response.txt
            exit 1
          fi

      - name: Upload get-weather response
        uses: actions/upload-artifact@v4
        with:
          name: get-weather-response
          path: get_weather_response.txt
